"""add model_url to item_personalizado

Revision ID: 23246b1b033b
Revises: 41de17472922
Create Date: 2025-11-12 03:16:09.616311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23246b1b033b'
down_revision: Union[str, Sequence[str], None] = '41de17472922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_personalizado', sa.Column('model_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_personalizado', 'model_url')
    # ### end Alembic commands ###
