"""Base schema fresh

Revision ID: 41de17472922
Revises: 
Create Date: 2025-11-08 16:48:09.641977

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41de17472922'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=True),
    sa.Column('rut', sa.String(), nullable=True),
    sa.Column('direccion', sa.String(), nullable=True),
    sa.Column('comentarios', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_id'), 'cliente', ['id'], unique=False)
    op.create_table('modelo_catalogo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('precio_base', sa.Float(), nullable=False),
    sa.Column('archivo_id', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('svg', sa.Text(), nullable=True),
    sa.Column('textura_imagen_id', sa.String(), nullable=True),
    sa.Column('parametros_generacion_ai', sa.JSON(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modelo_catalogo_id'), 'modelo_catalogo', ['id'], unique=False)
    op.create_table('item_personalizado',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('modelo_catalogo_id', sa.Integer(), nullable=True),
    sa.Column('nombre_personalizado', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('parametros', sa.JSON(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modelo_catalogo_id'], ['modelo_catalogo.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_personalizado_id'), 'item_personalizado', ['id'], unique=False)
    op.create_table('cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_personalizado_id', sa.String(), nullable=False),
    sa.Column('nombre_personalizado', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('moneda', sa.String(length=5), nullable=False),
    sa.Column('cotizacion_min', sa.Float(), nullable=False),
    sa.Column('cotizacion_max', sa.Float(), nullable=False),
    sa.Column('desglose', sa.JSON(), nullable=False),
    sa.Column('tiempo_entrega_dias', sa.Integer(), nullable=False),
    sa.Column('valida_hasta', sa.DateTime(), nullable=False),
    sa.Column('notas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_personalizado_id'], ['item_personalizado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_personalizado_id')
    )
    op.create_index(op.f('ix_cotizacion_id'), 'cotizacion', ['id'], unique=False)
    op.create_table('nfc_enlace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_personalizado_id', sa.String(), nullable=True),
    sa.Column('short_code', sa.String(), nullable=False),
    sa.Column('url_destino_actual', sa.String(), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_personalizado_id'], ['item_personalizado.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_code')
    )
    op.create_index(op.f('ix_nfc_enlace_id'), 'nfc_enlace', ['id'], unique=False)
    op.create_table('nfc_visita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nfc_enlace_id', sa.Integer(), nullable=True),
    sa.Column('fecha_conteo', sa.Date(), nullable=False),
    sa.Column('conteo', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nfc_enlace_id'], ['nfc_enlace.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nfc_enlace_id', 'fecha_conteo', name='uq_nfc_enlace_fecha')
    )
    op.create_index(op.f('ix_nfc_visita_id'), 'nfc_visita', ['id'], unique=False)
    op.create_table('pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('cotizacion_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('cotizacion_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cotizacion_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_final', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('precio_total', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('estado', sa.String(), nullable=False),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=True),
    sa.Column('mensaje', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cotizacion_id'], ['cotizacion.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pedido_id'), 'pedido', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pedido_id'), table_name='pedido')
    op.drop_table('pedido')
    op.drop_index(op.f('ix_nfc_visita_id'), table_name='nfc_visita')
    op.drop_table('nfc_visita')
    op.drop_index(op.f('ix_nfc_enlace_id'), table_name='nfc_enlace')
    op.drop_table('nfc_enlace')
    op.drop_index(op.f('ix_cotizacion_id'), table_name='cotizacion')
    op.drop_table('cotizacion')
    op.drop_index(op.f('ix_item_personalizado_id'), table_name='item_personalizado')
    op.drop_table('item_personalizado')
    op.drop_index(op.f('ix_modelo_catalogo_id'), table_name='modelo_catalogo')
    op.drop_table('modelo_catalogo')
    op.drop_index(op.f('ix_cliente_id'), table_name='cliente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
