"""Update models for API endpoints

Revision ID: 57c6cfb2d220
Revises: d4959947c727
Create Date: 2025-11-06 19:43:25.194875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57c6cfb2d220'
down_revision: Union[str, Sequence[str], None] = 'd4959947c727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_personalizado', sa.Column('parametros', sa.JSON(), nullable=True))
    op.drop_column('item_personalizado', 'parametros_diseno')
    op.add_column('modelo_catalogo', sa.Column('archivo_id', sa.String(), nullable=True))
    op.add_column('modelo_catalogo', sa.Column('url', sa.String(), nullable=True))
    op.add_column('modelo_catalogo', sa.Column('svg', sa.Text(), nullable=True))
    op.add_column('modelo_catalogo', sa.Column('textura_imagen_id', sa.String(), nullable=True))
    op.add_column('modelo_catalogo', sa.Column('parametros_generacion_ai', sa.JSON(), nullable=True))
    op.add_column('modelo_catalogo', sa.Column('thumbnail_url', sa.String(), nullable=True))
    op.drop_column('modelo_catalogo', 'source_url')
    op.drop_column('modelo_catalogo', 'image_url')
    op.add_column('pedido', sa.Column('moneda', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pedido', 'moneda')
    op.add_column('modelo_catalogo', sa.Column('image_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('modelo_catalogo', sa.Column('source_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('modelo_catalogo', 'thumbnail_url')
    op.drop_column('modelo_catalogo', 'parametros_generacion_ai')
    op.drop_column('modelo_catalogo', 'textura_imagen_id')
    op.drop_column('modelo_catalogo', 'svg')
    op.drop_column('modelo_catalogo', 'url')
    op.drop_column('modelo_catalogo', 'archivo_id')
    op.add_column('item_personalizado', sa.Column('parametros_diseno', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('item_personalizado', 'parametros')
    # ### end Alembic commands ###
