"""Link Pedido to Cotizacion

Revision ID: 74393fb3eef1
Revises: 756db31fc6ef
Create Date: 2025-11-07 09:06:17.827763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74393fb3eef1'
down_revision: Union[str, Sequence[str], None] = '756db31fc6ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('cotizacion_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('pedido_item_personalizado_id_fkey'), 'pedido', type_='foreignkey')
    op.create_foreign_key(None, 'pedido', 'cotizacion', ['cotizacion_id'], ['id'], ondelete='CASCADE')
    op.drop_column('pedido', 'moneda')
    op.drop_column('pedido', 'item_personalizado_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pedido', sa.Column('item_personalizado_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pedido', sa.Column('moneda', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pedido', type_='foreignkey')
    op.create_foreign_key(op.f('pedido_item_personalizado_id_fkey'), 'pedido', 'item_personalizado', ['item_personalizado_id'], ['id'], ondelete='CASCADE')
    op.drop_column('pedido', 'cotizacion_id')
    # ### end Alembic commands ###
