"""Create cotizacion table

Revision ID: 756db31fc6ef
Revises: 098e1f72186d
Create Date: 2025-11-07 09:04:03.592451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756db31fc6ef'
down_revision: Union[str, Sequence[str], None] = '098e1f72186d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cotizacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_personalizado_id', sa.Integer(), nullable=False),
    sa.Column('nombre_personalizado', sa.String(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.Column('moneda', sa.String(length=5), nullable=False),
    sa.Column('cotizacion_min', sa.Float(), nullable=False),
    sa.Column('cotizacion_max', sa.Float(), nullable=False),
    sa.Column('desglose', sa.JSON(), nullable=False),
    sa.Column('tiempo_entrega_dias', sa.Integer(), nullable=False),
    sa.Column('valida_hasta', sa.DateTime(), nullable=False),
    sa.Column('notas', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['item_personalizado_id'], ['item_personalizado.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_personalizado_id')
    )
    op.create_index(op.f('ix_cotizacion_id'), 'cotizacion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cotizacion_id'), table_name='cotizacion')
    op.drop_table('cotizacion')
    # ### end Alembic commands ###
